services:
  redis:
    container_name: redis-stack
    image: redis/redis-stack:edge
    environment:
      - REDIS_ARGS=--appendonly yes
    ports:
      - '${REDIS_PORT}:6379'
      - '${REDIS_ADMIN_PORT}:8001'
    volumes:
      - data:/data

volumes:
  data:
