set dotenv-load

default:
    just --list

dev:
    poetry env use 3.10.14
    poetry install --no-root
    poetry run bash scripts/start_dev.sh

apply:
    cd infra && terraform init && terraform apply --auto-approve

destroy:
    cd infra && terraform destroy --auto-approve

test:
    poetry run pytest -s -v

test-coverage:
    poetry run pytest -v --cov=src --cov-config=.coveragerc --cov-report=term-missing

test-coverage-html:
    poetry run pytest -v --cov=src --cov-config=.coveragerc --cov-report=html