default:
    just --list

setup:
    poetry env use 3.10.14
    poetry install --no-root

crawl-url:
    just setup
    poetry run scrapy crawl oikotie_url

crawl:
    just setup
    poetry run scrapy crawl oikotie