services:
  dynamodb:
    image: amazon/dynamodb-local:latest
    healthcheck:
      test: ['CMD-SHELL', 'curl -v http://dynamodb:8000']
      interval: 3s
      timeout: 3s
      retries: 5
      start_period: 3s
    user: root
    ports:
      - '${DYNAMODB_PORT}:8000'
    volumes:
      - dynamodb-data:/home/dynamodblocal/data
    working_dir: /home/dynamodblocal
    command: '-jar DynamoDBLocal.jar -sharedDb -dbPath ./data'
    restart: always
  redis:
    container_name: redis-stack
    image: redis/redis-stack:edge
    environment:
      - REDIS_ARGS=--appendonly yes
    ports:
      - '${REDIS_PORT}:6379'
    volumes:
      - redis-data:/data

volumes:
  redis-data:
  dynamodb-data:
