default:
    just --list

# Run DynamoDB in Docker
dynamodb-up:
    bash run.sh dynamodb up

# Stop DynamoDB
dynamodb-down:
    bash run.sh dynamodb down

# Restart DynamoDB
dynamodb-restart:
    bash run.sh dynamodb restart

# Run Redis in Docker
redis-up:
    bash run.sh redis up

# Stop Redis
redis-down:
    bash run.sh redis down

# Restart Redis
redis-restart:
    bash run.sh redis restart

# Run all services
all-up:
    just dynamodb-up
    just redis-up
    just airflow-up

# Stop all services
all-down:
    just dynamodb-down
    just redis-down
    just airflow-down

# Restart all services
all-restart:
    just dynamodb-restart
    just redis-restart
    just airflow-restart
